# (Borlandish) Makefile for apsim InterfaceTest module

# APSROOT needs to be defined here if you don't specify it on the commmand line. eg.
#APSROOT=c:\progra~1\apsim33
#APSROOT=c:\development

# Platform specific defns
!include $(APSROOT)\APSBuild\platform.make

# Fortran compiler defns
!include $(APSROOT)\APSBuild\fortran.make

# The statically linked components of the engine interface
!include $(APSROOT)\APSBuild\ApsimComponentInterface.make

# Main target
source: ..\lib\InterfaceTest.dll
..\lib\InterfaceTest.dll: Registrations.obj InterfaceTest.obj $(STATICLINKEDOBJECTS)
	$(ECHO) $(STATICLINKEDOBJECTS) > linker.tmp
	$(ECHO) $(F90FLAGS) >> linker.tmp
	$(ECHO) $(F90LIBS) >> linker.tmp
	$(LF95) InterfaceTest.obj Registrations.obj \
 -export Main,wrapperDLL,respondToEvent,alloc_dealloc_instance,getInstance -exe ..\lib\InterfaceTest.dll @linker.tmp
	#$(RM) linker.tmp

InterfaceTest.obj: InterfaceTest.for
	$(ECHO) $(F90FLAGS) > compiler.tmp
	$(ECHO) $(F90INCLUDES) >> compiler.tmp
	$(ECHO) $(F90MODS) >> compiler.tmp
	$(LF95) -c InterfaceTest.for @compiler.tmp
	$(RM) compiler.tmp

Registrations.obj: Registrations.f90
Registrations.f90: ..\InterfaceTest.interface 
	$(APSROOT)\bin\CreateComponentInterfaceSource.exe ..\InterfaceTest.interface

clean:
	$(RM) ..\lib\InterfaceTest.dll Registrations.obj Registrations.f90 InterfaceTest.obj InterfaceTest.imp
