!---------------------------------------------
! Interface for FORTRAN modules.
! Autogenerated - do not modify manually
!---------------------------------------------
module ScienceAPI

   interface
      subroutine Write(Msg)
      ml_external Write
      character(len=*), intent(in) :: Msg
      end subroutine

      subroutine Error(Msg, IsFatal)
      ml_external Error
      character(len=*), intent(in) :: Msg
      logical, intent(in) :: IsFatal
      end subroutine

      subroutine Subscribe(name, proc)
      ml_external Subscribe
      character (len=*), intent(in) :: name
      integer, external :: proc
      end subroutine


   end interface
   interface get

      function GetBoolean(Name, Units, Optional, Value, Lower, Upper)
         ml_external GetBoolean
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         logical, intent(in out)         :: Value
         logical, intent(in)             :: Lower
         logical, intent(in)             :: Upper
         logical :: GetBoolean
      end function

      function GetInt(Name, Units, Optional, Value, Lower, Upper)
         ml_external GetInt
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         integer, intent(in out)         :: Value
         integer, intent(in)             :: Lower
         integer, intent(in)             :: Upper
         logical :: GetInt
      end function

      function GetFloat(Name, Units, Optional, Value, Lower, Upper)
         ml_external GetFloat
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         real, intent(in out)         :: Value
         real, intent(in)             :: Lower
         real, intent(in)             :: Upper
         logical :: GetFloat
      end function

      function GetDouble(Name, Units, Optional, Value, Lower, Upper)
         ml_external GetDouble
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         double precision, intent(in out)         :: Value
         double precision, intent(in)             :: Lower
         double precision, intent(in)             :: Upper
         logical :: GetDouble
      end function

      function GetString(Name, Units, Optional, Value, Lower, Upper)
         ml_external GetString
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         character(len=100), intent(in out)         :: Value
         character(len=100), intent(in)             :: Lower
         character(len=100), intent(in)             :: Upper
         logical :: GetString
      end function

      function GetBoolArray(Name, Units, Optional, Value, ArraySize, NumValues, Lower, Upper)
         ml_external GetBoolArray
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         logical, intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in) :: NumValues
         logical, intent(in)             :: Lower
         logical, intent(in)             :: Upper
         logical :: GetBoolArray
      end function

      function GetIntArray(Name, Units, Optional, Value, ArraySize, NumValues, Lower, Upper)
         ml_external GetIntArray
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         integer, intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in) :: NumValues
         integer, intent(in)             :: Lower
         integer, intent(in)             :: Upper
         logical :: GetIntArray
      end function

      function GetFloatArray(Name, Units, Optional, Value, ArraySize, NumValues, Lower, Upper)
         ml_external GetFloatArray
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         real, intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in) :: NumValues
         real, intent(in)             :: Lower
         real, intent(in)             :: Upper
         logical :: GetFloatArray
      end function

      function GetDoubleArray(Name, Units, Optional, Value, ArraySize, NumValues, Lower, Upper)
         ml_external GetDoubleArray
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         double precision, intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in) :: NumValues
         double precision, intent(in)             :: Lower
         double precision, intent(in)             :: Upper
         logical :: GetDoubleArray
      end function

      function GetStringArray(Name, Units, Optional, Value, ArraySize, NumValues, Lower, Upper)
         ml_external GetStringArray
         character(len=*), intent(in) :: Name
         character(len=*), intent(in) :: Units
      logical, intent(in) :: Optional
         character(len=100), intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in) :: NumValues
         character(len=100), intent(in)             :: Lower
         character(len=100), intent(in)             :: Upper
         logical :: GetStringArray
      end function


   end interface

   interface Read

      function ReadBoolean(Name, Optional, Value)
         ml_external ReadBoolean
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         logical, intent(in out)         :: Value
         logical :: ReadBoolean
      end function

      function ReadInt(Name, Optional, Value)
         ml_external ReadInt
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         integer, intent(in out)         :: Value
         logical :: ReadInt
      end function

      function ReadFloat(Name, Optional, Value)
         ml_external ReadFloat
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         real, intent(in out)         :: Value
         logical :: ReadFloat
      end function

      function ReadDouble(Name, Optional, Value)
         ml_external ReadDouble
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         double precision, intent(in out)         :: Value
         logical :: ReadDouble
      end function

      function ReadString(Name, Optional, Value)
         ml_external ReadString
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         character(len=100), intent(in out)         :: Value
         logical :: ReadString
      end function

      function ReadBoolArray(Name, Optional, Value, ArraySize, NumValues)
         ml_external ReadBoolArray
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         logical, intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in out) :: NumValues
         logical :: ReadBoolArray
      end function

      function ReadIntArray(Name, Optional, Value, ArraySize, NumValues)
         ml_external ReadIntArray
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         integer, intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in out) :: NumValues
         logical :: ReadIntArray
      end function

      function ReadFloatArray(Name, Optional, Value, ArraySize, NumValues)
         ml_external ReadFloatArray
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         real, intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in out) :: NumValues
         logical :: ReadFloatArray
      end function

      function ReadDoubleArray(Name, Optional, Value, ArraySize, NumValues)
         ml_external ReadDoubleArray
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         double precision, intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in out) :: NumValues
         logical :: ReadDoubleArray
      end function

      function ReadStringArray(Name, Optional, Value, ArraySize, NumValues)
         ml_external ReadStringArray
         character(len=*), intent(in) :: Name
         logical, intent(in) :: Optional
         character(len=100), intent(in out)         :: Value(*)
         integer, intent(in) :: ArraySize
         integer, intent(in out) :: NumValues
         logical :: ReadStringArray
      end function


   end interface

end module

