#=======================================================================
#-----------------------------------------------------------------------
#     Makefile for APSIM crop module
#-----------------------------------------------------------------------
#=======================================================================

LIB=	../lib/libcropmod.a

SRC=	Registrations.f90	\
	CropModData.for		\
	CropMod.for		\
	CropModMain.for

STATICOBJ=	../../../Shared/ComponentInterface/SimpleWrapper.o \
            ../../../Shared/ComponentInterface/EntryPoints.o   \
            ../../../Shared/ComponentInterface/FORTRANComponentWrapper.o   \
            ../../../Shared/ComponentInterface/datatypes.o

OBJ=	Registrations.o		\
	CropModData.o		\
	CropMod.o		\
	CropModMain.o		\
	$(STATICOBJ)

#-----------------------------------------------------------------------
# Compiler options

FC=		lf95
CPPFLAGS=	-I$(APSROOT)/apsim/infra/source		\
		-I$(APSROOT)/apsim/croptemp/source
FFLAGS=		--tp -nco --o0 --pca -nsav -trace -nchk -nin \
		--ml cdecl --staticlink

#-----------------------------------------------------------------------
# Required libraries

LDFLAGS=	-L$(APSROOT)/apsim/infra/lib		\
		-L$(APSROOT)/apsim/croptemp/lib		\
		-L/usr/lib

LIBS=		-lapsinfra -lcroptemp

#-----------------------------------------------------------------------
# The rules

all: $(LIB)

$(LIB):	$(OBJ)


FORCE:

clean:
	rm -f *.o *.mod

clobber:	clean
	rm -r $(LIB)

install: all
	cp $(LIB) $(APSROOT)/lib

%.o:	%.for
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<

%.o:	%.f90
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<


Registrations.o: Registrations.f90
Registrations.f90: ../cropmod.interface 
	$(APSROOT)/bin/CreateComponentInterfaceSource ../cropmod.interface
