[UserRuns_CarinaMoellerA]
Simulation_file=%apsuite/UserRuns/CarinaMoellerA/ghab2.con

[UserRuns_CarinaMoellerB]
Simulation_file=%apsuite/UserRuns/CarinaMoellerB/ghab2.con

[UserRuns_KirstenVerburgA]
Simulation_file=%apsuite/UserRuns/KirstenVerburgA/csu-p149.con

[UserRuns_KirstenVerburgB]
Simulation_file=%apsuite/UserRuns/KirstenVerburgB/ruther142.con

[UserRuns_KirstenVerburgB1]
Simulation_file=%apsuite/UserRuns/KirstenVerburgB1/p14-113.con

[UserRuns_KirstenVerburg_lucerneA]
Simulation_file=%apsuite/UserRuns/KirstenVerburg_lucerne/p12-97.con

[UserRuns_KirstenVerburg_lucerneB]
Simulation_file=%apsuite/UserRuns/KirstenVerburg_lucerne/p12-99.con

[UserRuns_leaf_record_bug]
Simulation_file=%apsuite/UserRuns/leaf_record_bug/lucerne.con

[UserRuns_radishbug]
Simulation_file=%apsuite/UserRuns/radishbug/legume_bug.con

[UserRuns_howardcox]
Simulation_file=%apsuite/UserRuns/howardcox/jambincerealonly1995.con

[UserRuns_graeme_sutton]
Simulation_file=%apsuite/UserRuns/graeme~1/RUN1.CON

[UserRuns_NIHRotations]
Simulation_file=%apsuite/UserRuns/nihrotations/Rotation.con

[UserRuns_DSG_Esperance]
Simulation_file=%apsuite/UserRuns/DSG_Esperance/WA_cropping.con

[UserRuns_MEP_Chinese]
Simulation_file=%apsuite/UserRuns/MEP_Chinese/gansu.con

[UserRuns_SugarWT]
Simulation_file=%apsuite/UserRuns/SugarWaterTable/SugarWT.con

[UserRuns_Whitbread_Zim_NxP]
Simulation_file=%apsuite/UserRuns/WhitbreadZimPxN/PxN.con
