#=======================================================================
#-----------------------------------------------------------------------
#     Makefile for APSIM soil nitrogen module
#-----------------------------------------------------------------------
#=======================================================================

DESTDIR ?= /usr/local/apsim

LIB=	../lib/soiln2.so

SRC=	soiln2.f90

STATICOBJ=	../../../Shared/ComponentInterface/SimpleWrapper.o \
            ../../../Shared/ComponentInterface/EntryPoints.o   \
            ../../../Shared/ComponentInterface/FORTRANComponentWrapper.o   \
            ../../../Shared/ComponentInterface/FORTRANdatatypes.o   \
            ../../../Shared/ComponentInterface/datatypes.o

OBJ=	soiln2.o $(STATICOBJ)

#-----------------------------------------------------------------------
# Compiler options

FC=		lf95
CPPFLAGS=	-I$(APSROOT)/apsim/infra/source		\
		-M. -M$(APSROOT)/apsim/infra/source $(CPPDEBUGFLAGS)
FFLAGS=		--tp -nco --o0 --pca -nsav -trace -nchk -nin \
		--ml cdecl --staticlink

#-----------------------------------------------------------------------
# Required libraries

LDFLAGS=	-L$(APSROOT)/lib		\
		-L$(APSROOT)/apsim/infra/lib	 \
		-L/usr/lib $(LDDEBUGFLAGS)

LIBS=		-lComponentInterface -lapsinfra -lc

#-----------------------------------------------------------------------
# The rules

all: $(LIB)

$(LIB):	$(OBJ)
	g++ $(OBJ) -o $(LIB) -shared $(LDFLAGS) $(LIBS)

FORCE:

clean:
	rm -f *.o *.mod

clobber:	clean
	rm -f $(LIB)

install: all
	if [ ! -d $(DESTDIR)/apsim/soiln2/lib ]; then mkdir -p $(DESTDIR)/apsim/soiln2/lib; fi 
	cp $(LIB) $(DESTDIR)/apsim/soiln2/lib
	cp ../soiln2.ini $(DESTDIR)/apsim/soiln2

%.o:	%.for
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<

%.o:	%.f90
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<

