#=======================================================================
#-----------------------------------------------------------------------
#     Makefile for APSIM soil nitrogen module
#-----------------------------------------------------------------------
#=======================================================================

LIB=	../lib/soiln2.so

SRC=	Registrations.f90	\
	soiln2.f90

STATICOBJ=	../../../Shared/ComponentInterface/SimpleWrapper.o \
            ../../../Shared/ComponentInterface/EntryPoints.o   \
            ../../../Shared/ComponentInterface/FORTRANComponentWrapper.o   \
            ../../../Shared/ComponentInterface/FORTRANdatatypes.o   \
            ../../../Shared/ComponentInterface/datatypes.o

OBJ=	Registrations.o		\
	soiln2.o		\
	$(STATICOBJ)

#-----------------------------------------------------------------------
# Compiler options

FC=		lf95
CPPFLAGS=	-I$(APSROOT)/apsim/infra/source		\
		-M. -M$(APSROOT)/apsim/infra/source $(CPPDEBUGFLAGS)
FFLAGS=		--tp -nco --o0 --pca -nsav -trace -nchk -nin \
		--ml cdecl --staticlink

#-----------------------------------------------------------------------
# Required libraries

LDFLAGS=	-L$(APSROOT)/lib		\
		-L$(APSROOT)/apsim/infra/lib	 \
		-L/usr/lib $(LDDEBUGFLAGS)

LIBS=		-lComponentInterface -lapsinfra -lc

#-----------------------------------------------------------------------
# The rules

all: $(LIB)

$(LIB):	$(OBJ)
	g++ $(OBJ) -o $(LIB) -shared $(LDFLAGS) $(LIBS)

FORCE:

clean:
	rm -f *.o *.mod

clobber:	clean
	rm -f $(LIB)

install: all

%.o:	%.for
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<

%.o:	%.f90
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<


Registrations.o: Registrations.f90
Registrations.f90: ../soiln2.interface 
	$(APSROOT)/Bin/CreateComponentInterfaceSource ../soiln2.interface
