[accum]
Simulation_file=%apsuite/apsim/accum/sample/accum.con

[apswim]
Simulation_file=%apsuite/apsim/apswim/sample/apswim.con

[apswim_test]
Simulation_file=%apsuite/apsim/apswim/test/test.con

[bambatsi]
Simulation_file=%apsuite/apsim/Bambatsi/Sample/bambatsi.con

[barley]
Simulation_file=%apsuite/apsim/barley/Sample/barley.con

[broccoli]
Simulation_file=%apsuite/apsim/broccoli/sample/broccoli.con

[butterflypea]
Simulation_file=%apsuite/apsim/butterflypea/sample/butterflypea.apsim

[canola]
Simulation_file=%apsuite/apsim/canola/sample/canola.con

[canopy]
Simulation_file=%apsuite/apsim/canopy/sample/canopy.con

[canopy-apsim]
Simulation_file=%apsuite/apsim/canopy/sample/canopy sample.apsim

[chickpea]
Simulation_file=%apsuite/apsim/chickpea/Sample/chickpea.con

[chickpea sensibility]
Simulation_file=%apsuite/apsim/chickpea/Sensibility/chickpea.con

[clock]
Simulation_file=%apsuite/apsim/clock/sample/test.con

[correl]
Simulation_file=%apsuite/apsim/correl/sample/sample.con

[cowpea]
Simulation_file=%apsuite/apsim/cowpea/sample/cowpea.con

[cowpea PSample]
Simulation_file=%apsuite/apsim/cowpea/PSample/cowpea.con

[cropmod]
Simulation_file=%apsuite/apsim/CropMod/Sample/sample.con

[cropmod test maize]
Simulation_file=%apsuite/apsim/CropMod/Test/test.con

[cropmod test sorghum]
Simulation_file=%apsuite/apsim/CropMod/Test/testsorghum.con

[cropmod test sunflower]
Simulation_file=%apsuite/apsim/CropMod/Test/testsunflower.con

[economics]
Simulation_file=%apsuite/apsim/economics/sample/economics.apsim

[Egrandis sample]
Simulation_file=%apsuite/apsim/egrandis/sample/egrandis.con

[Egrandis]
Simulation_file=%apsuite/apsim/egrandis/validation/validation.con

[eo]
Simulation_file=%apsuite/apsim/eo/sample/sample.con

[erosion refset]
Simulation_file=%apsuite/apsim/erosion/RefSet/refdata.con

[erosion sample]
Simulation_file=%apsuite/apsim/erosion/sample/erosion.con

[fababean]
Simulation_file=%apsuite/apsim/fababean/Sample/fababean.con

[fababean sensibility]
Simulation_file=%apsuite/apsim/fababean/Sensibility/Fababean.con

[FarmwiseSequencer]
Simulation_file=%apsuite/apsim/FarmwiseSequencer/sample/FarmwiseSequencer.sim

[fertiliz]
Simulation_file=%apsuite/apsim/fertiliz/sample/fertiliz.con

[fieldpea]
Simulation_file=%apsuite/apsim/fieldpea/sample/fieldpea.con

[frmrpt]
Simulation_file=%apsuite/apsim/frmrpt/sample/frm1.con

[grasp refset]
Simulation_file=%apsuite/apsim/grasp/refset/refdata.con

[grasp sample]
Simulation_file=%apsuite/apsim/grasp/sample/grasp.con

[horsegram]
Simulation_file=%apsuite/apsim/Horsegram/Sample/horsegram.con

[input]
Simulation_file=%apsuite/apsim/input/sample/input.con

[irrigate]
Simulation_file=%apsuite/apsim/irrigate/sample/irrigate.con

[lucerne]
Simulation_file=%apsuite/apsim/lucerne/Sample/lucerne.con

[lablab]
Simulation_file=%apsuite/apsim/lablab/Sample/sample.con

[lupin]
Simulation_file=%apsuite/apsim/lupin/Sample/lupin.con

[maize refset]
Simulation_file=%apsuite/apsim/maize/RefSet/referenc.con

[maize sample]
Simulation_file=%apsuite/apsim/maize/Sample/maize.con

[maize sensibility]
Simulation_file=%apsuite/apsim/maize/Sensibility/maize.con

[maize Psample]
Simulation_file=%apsuite/apsim/maize/PSample/sample.con

[manager sample1]
Simulation_file=%apsuite/apsim/manager/sample/manager.con

[manager test]
Simulation_file=%apsuite/apsim/manager/test/test.con

[map]
Simulation_file=%apsuite/apsim/map/sample/map.con

[met]
Simulation_file=%apsuite/apsim/met/sample/met.con

[micromet sample]
Simulation_file=%apsuite/apsim/micromet/sample/micromet.con

[millet refset]
Simulation_file=%apsuite/apsim/millet/refset/valid_1.con

[millet test]
Simulation_file=%apsuite/apsim/millet/test/test.con

[millet sample]
Simulation_file=%apsuite/apsim/millet/sample/millet.con

[mucuna]
Simulation_file=%apsuite/apsim/mucuna/sample/mucuna.con

[multipoint]
Simulation_file=%apsuite/apsim/multipoint/sample/multipoint.sim

[multipoint test]
Simulation_file=%apsuite/apsim/multipoint/test/testerrorpropagation.sim

[mungbean]
Simulation_file=%apsuite/apsim/mungbean/Sample/mungbean.con

[mungbean PSample]
Simulation_file=%apsuite/apsim/mungbean/PSample/mungbean.con

[mungbean sensibility]
Simulation_file=%apsuite/apsim/mungbean/Sensibility/mungbean.con

[navybean]
Simulation_file=%apsuite/apsim/navybean/Sample/navybean.con

[navybean PSample]
Simulation_file=%apsuite/apsim/navybean/PSample/navybean.con

[operatns]
Simulation_file=%apsuite/apsim/operatns/sample/operatns.con

[ozcot]
Simulation_file=%apsuite/apsim/ozcot/sample/ozcot.con

[Parasite]
Simulation_file=%apsuite/apsim/parasite/Sample/sample.con

[Pasture]
Simulation_file=%apsuite/apsim/pasture/sample/pasture.sim

[PatchInput]
Simulation_file=%apsuite/apsim/PatchInput/sample/PatchInput.con

[peanut]
Simulation_file=%apsuite/apsim/peanut/Sample/peanut.con

[peanut PSample]
Simulation_file=%apsuite/apsim/peanut/PSample/peanut.con

[pigeonp]
Simulation_file=%apsuite/apsim/pigeonp/sample/pigeonp.con

[pigeonp PSample]
Simulation_file=%apsuite/apsim/pigeonp/PSample/pigeonp.con

[plant]
Simulation_file=%apsuite/apsim/Plant/RefSet/referenc.con

[plant test]
Simulation_file=%apsuite/apsim/Plant/Test/test.con

[plant Psample]
Simulation_file=%apsuite/apsim/Plant/PSample/sample.con

[report sample1]
Simulation_file=%apsuite/apsim/report/sample/report.con

[siloinput sample]
Simulation_file=%apsuite/apsim/siloinput/sample/siloinput.con

[slurp]
Simulation_file=%apsuite/apsim/slurp/sample/slurp.con

[soi]
Simulation_file=%apsuite/apsim/soi/sample/run.con

[soiln2]
Simulation_file=%apsuite/apsim/soiln2/sample/soiln2.con

[soiln2test]
Simulation_file=%apsuite/apsim/soiln2/test/test.con

[soilp]
Simulation_file=%apsuite/apsim/SoilP/sample/soilp.con

[soilptest]
Simulation_file=%apsuite/apsim/SoilP/test/test.con

[soilt sample]
Simulation_file=%apsuite/apsim/soilt/sample/soilt.con

[soiltemp sample]
Simulation_file=%apsuite/apsim/soiltemp/sample/soiltemp.con

[soilwat2 refset]
Simulation_file=%apsuite/apsim/soilwat2/RefSet/refdata.con

[soilwat2 sample]
Simulation_file=%apsuite/apsim/soilwat2/sample/soilwat2.con

[soilwat2 test]
Simulation_file=%apsuite/apsim/soilwat2/test/soilwat2_test.con

[solute]
Simulation_file=%apsuite/apsim/solute/sample/solute.con

[sorghum]
Simulation_file=%apsuite/apsim/sorghum/sample/sorghum.con

[sorghum PSample]
Simulation_file=%apsuite/apsim/sorghum/PSample/sample.con

[sorghum sensibility]
Simulation_file=%apsuite/apsim/sorghum/Sensibility/sorghum.con

[soybean]
Simulation_file=%apsuite/apsim/soybean/sample/soybean.con

[soybean PSample]
Simulation_file=%apsuite/apsim/soybean/PSample/soybean.con

[stock]
Simulation_file=%apsuite/apsim/stock/sample/stock.sim

[stylo]
Simulation_file=%apsuite/apsim/stylo/Sample/stylo.con

[sugar refset]
Simulation_file=%apsuite/apsim/sugar/RefSet/referenc.con

[sugar sample]
Simulation_file=%apsuite/apsim/sugar/Sample/sugar.con

[sugar test]
Simulation_file=%apsuite/apsim/sugar/Test/test.con

[sugar testA]
Simulation_file=%apsuite/apsim/sugar/Test/testA.con

[sunflower]
Simulation_file=%apsuite/apsim/sunflower/Sample/sunflower.con

[sunflower_validation]
Simulation_file=%apsuite/apsim/sunflower/Validation/valid.con

[Supplement]
Simulation_file=%apsuite/apsim/Supplement/sample/supplement stock only.sim

[surface]
Simulation_file=%apsuite/apsim/surface/sample/sample.con

[surfaceOM]
Simulation_file=%apsuite/apsim/SurfaceOM/sample/surfaceom.con

[surfaceomtest]
Simulation_file=%apsuite/apsim/SurfaceOM/test/test.con

[sweetcorn]
Simulation_file=%apsuite/apsim/sweetcorn/Sample/sweetcorn.con

![sweetcorn_validation]
!Simulation_file=%apsuite/apsim/sweetcorn/Validation/sweetcorn.apsim

[sweetsorghum]
Simulation_file=%apsuite/apsim/SweetSorghum/Sample/sweetsorghum.con

[sweetsorghum_validation]
Simulation_file=%apsuite/apsim/SweetSorghum/Validation/sweetsorghum.con

[sysbal]
Simulation_file=%apsuite/apsim/SysBal/sample/sysbal.con

[tamet2]
Simulation_file=%apsuite/apsim/tamet2/sample/sample.con

[tcllink]
Simulation_file=%apsuite/apsim/tcllink/Sample/tcllink.con

[tracker]
Simulation_file=%apsuite/apsim/Tracker/Sample/tracker.con

[tree]
Simulation_file=%apsuite/apsim/tree/refset/refdata.con

[tree step1]
Simulation_file=%apsuite/apsim/tree/test/step1/tree.con

[tree step2]
Simulation_file=%apsuite/apsim/tree/test/step2/tree.con

;[UserRuns_CarinaMoellerA]
;Simulation_file=%apsuite/apsim/UserRuns/CarinaMoellerA/ghab2.con
;
;[UserRuns_CarinaMoellerB]
;Simulation_file=%apsuite/apsim/UserRuns/CarinaMoellerB/ghab2.con
;
;[UserRuns_KirstenVerburgA]
;Simulation_file=%apsuite/apsim/UserRuns/KirstenVerburgA/csu-p149.con
;
;[UserRuns_KirstenVerburgB]
;Simulation_file=%apsuite/apsim/UserRuns/KirstenVerburgB/ruther142.con
;
;[UserRuns_KirstenVerburgB1]
;Simulation_file=%apsuite/apsim/UserRuns/KirstenVerburgB1/p14-113.con
;
;[UserRuns_KirstenVerburg_lucerneA]
;Simulation_file=%apsuite/apsim/UserRuns/KirstenVerburg_lucerne/p12-97.con
;
;[UserRuns_KirstenVerburg_lucerneB]
;Simulation_file=%apsuite/apsim/UserRuns/KirstenVerburg_lucerne/p12-99.con
;
;[UserRuns_leaf_record_bug]
;Simulation_file=%apsuite/apsim/UserRuns/leaf_record_bug/lucerne.con
;
;[UserRuns_radishbug]
;Simulation_file=%apsuite/apsim/UserRuns/radishbug/legume_bug.con
;
;[UserRuns_howardcox]
;Simulation_file=%apsuite/apsim/UserRuns/howardcox/jambincerealonly1995.con
;
;[UserRuns_graeme_sutton]
;Simulation_file=%apsuite/apsim/UserRuns/graeme~1/RUN1.CON

[venlink]
Simulation_file=%apsuite/apsim/venlink/sample/vensim.con

[watersupply]
Simulation_file=%apsuite/apsim/WaterSupply/sample/watersupply.con

[weed]
Simulation_file=%apsuite/apsim/weed/sample/weed.con

[wheat]
Simulation_file=%apsuite/apsim/Wheat/Sample/wheat.con

[wheat_sensibility]
Simulation_file=%apsuite/apsim/Wheat/Sensibility/wheat.con

[oryza]
Simulation_file=%apsuite/apsim/oryza/sample/oryza.con
