#include <classlib\arrays.h>

typedef TArrayAsVector <long> Int_array;

#include <gobjs\gobjs.h>

// *******************************************************************
      int GOBJS_FUNCTION_EXPORT Find_int_in_array(int Integer, int Arr[], int Num_elements);
// *******************************************************************

//  Short description:
//    Find the specified integer in the specified integer array.

// *******************************************************************
      int GOBJS_FUNCTION_EXPORT Find_maximum_in_int_array(int Arr[], int Num_elements);
// *******************************************************************

//  Short description:
//    Find the maximum integer in the specified integer array.

// *******************************************************************
      int GOBJS_FUNCTION_EXPORT Count_ints_in_array(int Integer, int Arr[], int Num_elements);
// *******************************************************************

//  Short description:
//    Count the number of times the specified integer is in the specified array.

