#=======================================================================
#-----------------------------------------------------------------------
#     Makefile for APSIM clock module
#-----------------------------------------------------------------------
#=======================================================================
DESTDIR ?= /usr/local/apsim

LIB=	../lib/accum.so

SRC=	Registrations.f90	\
	accum.for

STATICOBJ=	$(APSROOT)/Shared/ComponentInterface/SimpleWrapper.o	\
	$(APSROOT)/Shared/ComponentInterface/FORTRANComponentWrapper.o 	\
	$(APSROOT)/Shared/ComponentInterface/EntryPoints.o 		\
	$(APSROOT)/Shared/ComponentInterface/FORTRANdatatypes.o 		\
	$(APSROOT)/Shared/ComponentInterface/datatypes.o

OBJ=	Registrations.o		\
	accum.o			\
	$(STATICOBJ)

#-----------------------------------------------------------------------
# Compiler options

FC=		lf95
CPPFLAGS=	-I$(APSROOT)/apsim/infra/source		\
		-M. -M$(APSROOT)/apsim/infra/source $(CPPDEBUGFLAGS)
FFLAGS=		--tp -nco --o0 --pca -nsav -trace -nchk -nin 	\
		--ml cdecl --staticlink

#-----------------------------------------------------------------------
# Required libraries

LDFLAGS=	-L$(APSROOT)/lib		\
		-L$(APSROOT)/apsim/infra/lib	\
		-L/usr/lib $(LDDEBUGFLAGS)

LIBS=		-lComponentInterface 		\
		-lapsinfra			\
		-lc

#-----------------------------------------------------------------------
# The rules

all: $(LIB)

$(LIB):	$(OBJ)
	g++ $(OBJ) -o $(LIB) -shared $(LDFLAGS) $(LIBS)

FORCE:

install: all
	if [ ! -d $(DESTDIR)/apsim/accum/lib ]; then mkdir -p $(DESTDIR)/apsim/accum/lib; fi 
	cp $(LIB) $(DESTDIR)/apsim/accum/lib

clean:
	rm -f *.o *.mod

clobber:	clean
	rm -f $(LIB)

%.o:	%.for
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<

%.o:	%.f90
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<


Registrations.o: Registrations.f90
Registrations.f90: ../accum.interface 
	$(APSROOT)/Bin/CreateComponentInterfaceSource ../accum.interface
