#=======================================================================
#-----------------------------------------------------------------------
#     Makefile for APSIM clock module
#-----------------------------------------------------------------------
#=======================================================================

LIB=	../lib/libclock.so

SRC=	Registrations.f90	\
	clock.for		\
	clock_read_params.for

STATICOBJ=	$(APSROOT)/Shared/ComponentInterface/SimpleWrapper.o	\
	$(APSROOT)/Shared/ComponentInterface/FORTRANComponentWrapper.o 	\
	$(APSROOT)/Shared/ComponentInterface/EntryPoints.o 		\
	$(APSROOT)/Shared/ComponentInterface/datatypes.o

OBJ=	Registrations.o		\
	clock.o			\
	clock_read_params.o	\
	$(STATICOBJ)

#-----------------------------------------------------------------------
# Compiler options

FC=		lf95
CPPFLAGS=	-I$(APSROOT)/apsim/infra/source		\
		-M. -M$(APSROOT)/apsim/infra/source
FFLAGS=		--tp -nco --o0 --pca -nsav -trace -nchk -nin 	\
		--ml cdecl --staticlink

#-----------------------------------------------------------------------
# Required libraries

LDFLAGS=	-L$(APSROOT)/lib		\
		-L$(APSROOT)/apsim/infra/lib	\
		-L/usr/lib

LIBS=		-lComponentInterface 		\
		-lapsinfra			\
		-lc

#-----------------------------------------------------------------------
# The rules

all: $(LIB)

$(LIB):	$(OBJ)
	g++ $(OBJ) -o $(LIB) -shared $(LDFLAGS) $(LIBS)

FORCE:

clean:
	rm -f *.o *.mod

clobber:	clean
	rm -r $(LIB)

%.o:	%.for
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<

%.o:	%.f90
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<







