#=======================================================================
#-----------------------------------------------------------------------
#     Makefile for APSIM manager module
#-----------------------------------------------------------------------
#=======================================================================

LIB=	../lib/libmanager.so

SRC=	Registrations.f90	\
	manager.for

STATICOBJ=	../../../Shared/ComponentInterface/SimpleWrapper.o \
            ../../../Shared/ComponentInterface/EntryPoints.o   \
            ../../../Shared/ComponentInterface/FORTRANComponentWrapper.o   \
            ../../../Shared/ComponentInterface/datatypes.o

OBJ=	Registrations.o		\
	manager.o		\
	$(STATICOBJ)

#-----------------------------------------------------------------------
# Compiler options

FC=		lf95
CPPFLAGS=	-I$(APSROOT)/apsim/infra/source		\
		-M. -M$(APSROOT)/apsim/infra/source
FFLAGS=		--tp -nco --o0 --pca -nsav -trace -nchk -nin \
		--ml cdecl --staticlink

#-----------------------------------------------------------------------
# Required libraries

LDFLAGS=	-L$(APSROOT)/lib		\
		-L$(APSROOT)/apsim/infra/lib	 \
		-L/usr/lib

LIBS=		-lComponentInterface -lapsinfra -lc

#-----------------------------------------------------------------------
# The rules

all: $(LIB)

$(LIB):	$(OBJ)
	g++ $(OBJ) -o $(LIB) -shared $(LDFLAGS) $(LIBS)

FORCE:

clean:
	rm -f *.o *.mod

clobber:	clean
	rm -f $(LIB)

install: all
	cp $(LIB) $(APSROOT)/lib

%.o:	%.for
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<

%.o:	%.f90
	$(FC) $(CPPFLAGS) $(FFLAGS) -c -o $@ $<


Registrations.o: Registrations.f90
Registrations.f90: ../manager.interface 
	$(APSROOT)/bin/CreateComponentInterfaceSource ../manager.interface
